apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # pvc
  name: ce-aa-std-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ce-aa-rwmany
  resources:
    requests:
      storage: 1Gi