apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # pvc
  name: prod-cepg-aa-std-pvc
  namespace: "82230188"
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: cepg-aa-std-rwmany
  resources:
    requests:
      storage: 1Gi